### ISSUE TITLE
Vibration feedback .. enhancement

### ISSUE THREAD

**Issue by adolfotregosa** [NeroReflex/ROGueENEMY#9] opened 2023-12-13 23:52 UTC
...when changing controller mode on the rog ally.

Please.

Thank you

**Comment by NeroReflex** [comment] 2023-12-13 23:54
Duplicate of https://github.com/NeroReflex/ROGueENEMY/issues/8 except for feedback type. What do you want?

**Comment by adolfotregosa** [comment] 2023-12-13 23:56
I want vibration

**Closed as completed** 2023-12-20 12:00 UTC
Labels: enhancement
